### ISSUE TITLE
Installer Stuck at Boot

### ISSUE THREAD

**Issue by mmathys** [thenephilim13/macOS#2]
Hello there, I am having an issue that my installer is stuck at boot. Please see my specs:

### Details

**Motherboard**: ASUS Prime Z370-A II
**CPU**: Intel i7-8700
**RAM**: Corsair Vengeance LPX (2x 8GB, DDR4-3200)
**Graphics Card**: RX 580 (Saphire Nitro+)
**NVMe**: Samsung 970 EVO Plus (1 x 1TB, 1 x 500GB)
**SSD**: none

**Drivers**: 
- As mentioned in vanilla guide: `ApfsDriverLoader.efi`, `FwRuntimeServices.efi`, `UsbKbDxe.efi`, `VBoxHfs.efi`
- Driver for VirtualSMC: `VirtualSmc.efi`

**Kexts**: I'm using the very same kexts like described in the README. Generated `AGPMInjector.kext` with iMac19,1 and RX580

**ACPI**: I copied the dsl files referenced in `config.plist` to `EFI/OC/ACPI` (not `/EFI/OC/ACPI/patched`). They are the following:
- `SSDT-EC-USBX.dsl`
- `SSDT-PLUG.dsl`
- `SSDT-UIAC-ALL.dsl`

I am not sure whether this is enough.

**config.plist**: Exact copy

Complete OC drive: [OC.zip](https://github.com/thenephilim13/macOS/files/4015420/OC.zip)

Log:

![IMG_20200102_103614](https://user-images.githubusercontent.com/5797176/71660599-d8201600-2d4b-11ea-9cc7-6897decac31b.jpg)

### Notes

First of all, I am not sure what the problem is. Maybe it could be that the EC SSDT is not correct, [similar to this issue](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/troubleshooting#stalling-on-apfs_module_start-waiting-for-root-device-waiting-on-ioresources-previous-shutdown-cause-in-catalina). Maybe some SSDT files are missing?

@thenephilim13, would you be able to look over these steps real quick and give me a hint what the error could be? :)

**Comment by mmathys** [comment]
Sorry – I did not assemble the ACPI files 😅after compiling the .dsl files to .aml assembly with MaciASL it works flawlessly. Thank you a lot for the configuration!

**Comment by thenephilim13** [comment]
@mmathys Glad you figured it out and it's working well for you!

**Comment by thenephilim13** [comment]
I've updated the README a bit more for extra clarity & tips
